Adapt Holonix automation to this repo

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -10,6 +10,10 @@ jobs:
   nix-check:
     runs-on: ubuntu-latest
 
+    permissions:
+      contents: read
+      id-token: write
+
     steps:
       - name: Check out source code
         uses: actions/checkout@v4
@@ -19,11 +23,41 @@ jobs:
         with:
           install_url: https://releases.nixos.org/nix/nix-2.22.1/install
 
+      - name: Use GitHub cache
+        uses: DeterminateSystems/magic-nix-cache-action@main
+
       - name: Check Nix formatting
         run: nix fmt . -- --check
 
       - name: Check Nix flake
         run: nix flake check --all-systems
+
+  script-test:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ludeeus/action-shellcheck@v2
+
+      - name: Test bump-holochain.sh
+        run: |
+          MINOR_VERSION=$(./scripts/bump.sh main-0.1 false | tail -n 1)
+          if [[ "$MINOR_VERSION" != "0.1.8" ]]; then
+              echo "bump.sh failed to find 0.1.8: [${MINOR_VERSION}]"
+              exit 1
+          fi
+          
+          RC_VERSION=$(./scripts/bump.sh main-0.1-rc false | tail -n 1)
+          if [[ "$RC_VERSION" != "0.1.7-rc.0" ]]; then
+              echo "bump.sh failed to find 0.1.7-rc.0: [${RC_VERSION}]"
+              exit 1
+          fi
+          
+          CURRENT_VERSION=$(./scripts/bump.sh main false | tail -n 1)
+          if [[ "$CURRENT_VERSION" != 0.4.*dev* ]]; then
+              echo "bump.sh failed to find current version: [${CURRENT_VERSION}]"
+              exit 1
+          fi
 
   build:
     strategy:
